name: Validate data pack

on:
  workflow_dispatch:
  pull_request:

jobs:
  Mecha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mcbeet/check-commands@v1
        with:
          source: .
          minecraft: "1.20.4"
          stats: true
